name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
     - run: echo -e " This is a Test"
     - name: Checkout Repository
       uses: actions/checkout@v2
     - name: Change permission
       run: chmod +x scripts/test.sh
       
     - name: Run Test Script
       run: ./scripts/test.sh

     - name: Upload artifact
       uses: actions/upload-artifact@v3
       with:
         name: github-details
         path: /home/runner/github_details.txt
         
  job_2:
    runs-on: ubuntu-latest
    name: Display Artifact File
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: github-details
          path: $HOME

      - name: Display Artifact Content
        run: cat $HOME
